version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: betteruptime-postgres
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: betteruptime-redis
    restart: always

  # Run DB migrations once
  migrate:
    image: mrnikhillyadav/betteruptime-backend:latest
    container_name: betteruptime-migrate
    depends_on:
      - postgres
    env_file:
      - .env
    working_dir: /usr/src/app/packages/store
    command: bunx prisma migrate deploy
    restart: "no"

  backend:
    image: mrnikhillyadav/betteruptime-backend:latest
    container_name: betteruptime-backend
    restart: always
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis

  consumer:
    image: mrnikhillyadav/betteruptime-consumer:latest
    container_name: betteruptime-consumer
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  pusher:
    image: mrnikhillyadav/betteruptime-pusher:latest
    container_name: betteruptime-pusher
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  frontend:
    image: mrnikhillyadav/betteruptime-frontend:latest
    container_name: betteruptime-frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend

volumes:
  pgdata:
